# Generated by Django 5.2 on 2025-11-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronicproduct',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='toyproduct',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='womenproduct',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='electronicproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='temp/'),
        ),
        migrations.AlterField(
            model_name='toyproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='temp/'),
        ),
        migrations.AlterField(
            model_name='womenproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='temp/'),
        ),
    ]
