# Generated by Django 5.2 on 2025-11-07 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_electronicproduct_image_url_toyproduct_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electronicproduct',
            name='image',
        ),
        migrations.RemoveField(
            model_name='toyproduct',
            name='image',
        ),
        migrations.RemoveField(
            model_name='womenproduct',
            name='image',
        ),
    ]
