# Generated by Django 5.2 on 2025-11-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_businessnameandlogo_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessnameandlogo',
            name='allowed_pincodes',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
