# Generated by Django 5.2 on 2025-11-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_cartitem_color_cartitem_fabric_cartitem_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='womenproduct',
            name='category',
            field=models.CharField(choices=[('sarees', 'Sarees'), ('accessories', 'Accessories'), ('footwear', 'Footwear')], default='tops', max_length=50),
        ),
    ]
