# Generated by Django 5.2 on 2025-12-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_payment_id_order_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash On Delivery'), ('CARD', 'Credit / Debit Card'), ('UPI', 'UPI Payment')], default='COD', max_length=100),
        ),
    ]
