# Generated by Django 5.2 on 2025-11-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_womenproduct_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paid',
            field=models.BooleanField(choices=[('Paid', 'Paid'), ('Not Paid', 'Not Paid')], default='Not Paid'),
        ),
    ]
