# Generated by Django 5.2 on 2025-11-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_order_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronicproduct',
            name='available_stock',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='toyproduct',
            name='available_stock',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='womenproduct',
            name='available_stock',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
