# Generated by Django 5.2 on 2025-11-12 19:16

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_electronicproduct_available_stock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electronicproduct',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='toyproduct',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='womenproduct',
            name='image_url',
        ),
        migrations.AddField(
            model_name='electronicproduct',
            name='image',
            field=cloudinary.models.CloudinaryField(default='default.jpg', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='toyproduct',
            name='image',
            field=cloudinary.models.CloudinaryField(default='default.jpg', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='womenproduct',
            name='image',
            field=cloudinary.models.CloudinaryField(default='default.jpg', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='womenproduct',
            name='category',
            field=models.CharField(choices=[('sarees', 'Sarees'), ('accessories', 'Accessories'), ('footwear', 'Footwear')], default='sarees', max_length=50),
        ),
    ]
