# Generated by Django 5.2 on 2025-11-15 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_order_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_delivery_boy',
            field=models.BooleanField(default=False),
        ),
    ]
