# Generated by Django 5.2 on 2025-11-16 11:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronicproduct',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='toyproduct',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='womenproduct',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
