# Generated by Django 5.2 on 2025-11-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_electronicproduct_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronicproduct',
            name='description_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='toyproduct',
            name='description_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='womenproduct',
            name='description_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='electronicproduct',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='toyproduct',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='womenproduct',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
