# Generated by Django 5.2 on 2025-11-18 17:13

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_deliveryprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessNameAndLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('logo', cloudinary.models.CloudinaryField(max_length=255, verbose_name='logo')),
            ],
        ),
    ]
