from .home import *
from .auth_otp import *
from .cart import *
from .wishlist import *
from .checkout import *
from .orders import *
from .admin_panel import *
from .product_detail import *
from .review import *
from .misc import *
from .delievery import *
from .category_products import * 